/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataIUP(tabelIUP, "SELECT*FROM iup");
        mycode.tampilDataKapal(tabelKapal, "SELECT*FROM kapal");
        mycode.tampilDataRealisasi(tabelReal, "SELECT*FROM realisasi");
        mycode.tampilDataCadangan(tabelCadangan, "SELECT*FROM cadangan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlKapal = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDlmGali = new javax.swing.JTextField();
        txtInstansi = new javax.swing.JTextField();
        btnHpsKpl = new javax.swing.JButton();
        btnSmpnKpl = new javax.swing.JButton();
        btnUbhKpl = new javax.swing.JButton();
        txtCariKpl = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelKapal = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtNmKpl = new javax.swing.JTextField();
        pnlIup = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNoSk = new javax.swing.JTextField();
        txtLokasi = new javax.swing.JTextField();
        txtTglBerlaku = new javax.swing.JTextField();
        btnHpsIup = new javax.swing.JButton();
        btnSmpnIup = new javax.swing.JButton();
        btnUbhIup = new javax.swing.JButton();
        txtCariIup = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelIUP = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtNoIup = new javax.swing.JTextField();
        txtNoSert = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtKet = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        pnlCadangan = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtBulanCad = new javax.swing.JTextField();
        txtNmKplCad = new javax.swing.JTextField();
        txtTahunCad = new javax.swing.JTextField();
        btnHpsCad = new javax.swing.JButton();
        btnSmpnCad = new javax.swing.JButton();
        btnUbhCad = new javax.swing.JButton();
        txtCariCad = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelCadangan = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        txtKdCad = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtLuasCad = new javax.swing.JTextField();
        txtLautCad = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtNoIupCad = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtDdh = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtPdh = new javax.swing.JTextField();
        txtTdh = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtIdh = new javax.swing.JTextField();
        pnlRealisasi = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtDsb = new javax.swing.JTextField();
        txtKdCadReal = new javax.swing.JTextField();
        txtIsb = new javax.swing.JTextField();
        btnHpsReal = new javax.swing.JButton();
        btnSmpnReal = new javax.swing.JButton();
        btnUbhReal = new javax.swing.JButton();
        txtCariReal = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelReal = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtKdReal = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtPsb = new javax.swing.JTextField();
        txtTsb = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKapal = new javax.swing.JButton();
        btnIup = new javax.swing.JButton();
        btnCadangan = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnRealisasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlKapal.setBackground(new java.awt.Color(204, 204, 204));
        pnlKapal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Kedalaman Gali");
        pnlKapal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Instansi");
        pnlKapal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtDlmGali.setBackground(new java.awt.Color(255, 255, 255));
        txtDlmGali.setForeground(new java.awt.Color(0, 0, 0));
        pnlKapal.add(txtDlmGali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtInstansi.setBackground(new java.awt.Color(255, 255, 255));
        txtInstansi.setForeground(new java.awt.Color(0, 0, 0));
        txtInstansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstansiActionPerformed(evt);
            }
        });
        pnlKapal.add(txtInstansi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        btnHpsKpl.setText("HAPUS");
        btnHpsKpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKplActionPerformed(evt);
            }
        });
        pnlKapal.add(btnHpsKpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnKpl.setText("SIMPAN");
        btnSmpnKpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKplActionPerformed(evt);
            }
        });
        pnlKapal.add(btnSmpnKpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhKpl.setText("UBAH");
        btnUbhKpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKplActionPerformed(evt);
            }
        });
        pnlKapal.add(btnUbhKpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariKpl.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKpl.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKpl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKplKeyReleased(evt);
            }
        });
        pnlKapal.add(txtCariKpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 370, -1));

        tabelKapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelKapal);

        pnlKapal.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 480, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Nama Kapal");
        pnlKapal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtNmKpl.setBackground(new java.awt.Color(255, 255, 255));
        txtNmKpl.setForeground(new java.awt.Color(0, 0, 0));
        txtNmKpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmKplActionPerformed(evt);
            }
        });
        pnlKapal.add(txtNmKpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlKapal, "card4");

        pnlIup.setBackground(new java.awt.Color(204, 204, 204));
        pnlIup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Tanggal Berlaku");
        pnlIup.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("No SK");
        pnlIup.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Lokasi");
        pnlIup.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtNoSk.setBackground(new java.awt.Color(255, 255, 255));
        txtNoSk.setForeground(new java.awt.Color(0, 0, 0));
        pnlIup.add(txtNoSk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtLokasi.setBackground(new java.awt.Color(255, 255, 255));
        txtLokasi.setForeground(new java.awt.Color(0, 0, 0));
        txtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiActionPerformed(evt);
            }
        });
        pnlIup.add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTglBerlaku.setBackground(new java.awt.Color(255, 255, 255));
        txtTglBerlaku.setForeground(new java.awt.Color(0, 0, 0));
        pnlIup.add(txtTglBerlaku, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsIup.setText("HAPUS");
        btnHpsIup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsIupActionPerformed(evt);
            }
        });
        pnlIup.add(btnHpsIup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnIup.setText("SIMPAN");
        btnSmpnIup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnIupActionPerformed(evt);
            }
        });
        pnlIup.add(btnSmpnIup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhIup.setText("UBAH");
        btnUbhIup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhIupActionPerformed(evt);
            }
        });
        pnlIup.add(btnUbhIup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariIup.setBackground(new java.awt.Color(255, 255, 255));
        txtCariIup.setForeground(new java.awt.Color(0, 0, 0));
        txtCariIup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariIupKeyReleased(evt);
            }
        });
        pnlIup.add(txtCariIup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, -1));

        tabelIUP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelIUP);

        pnlIup.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 480, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("No IUP");
        pnlIup.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtNoIup.setBackground(new java.awt.Color(255, 255, 255));
        txtNoIup.setForeground(new java.awt.Color(0, 0, 0));
        txtNoIup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoIupActionPerformed(evt);
            }
        });
        pnlIup.add(txtNoIup, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtNoSert.setBackground(new java.awt.Color(255, 255, 255));
        txtNoSert.setForeground(new java.awt.Color(0, 0, 0));
        pnlIup.add(txtNoSert, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("No Sertifikat");
        pnlIup.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, -1));

        txtKet.setBackground(new java.awt.Color(255, 255, 255));
        txtKet.setForeground(new java.awt.Color(0, 0, 0));
        pnlIup.add(txtKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Keterangan");
        pnlIup.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, -1));

        Content.add(pnlIup, "card3");

        pnlCadangan.setBackground(new java.awt.Color(204, 204, 204));
        pnlCadangan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Tahun");
        pnlCadangan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Bulan");
        pnlCadangan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Nama Kapal ");
        pnlCadangan.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtBulanCad.setBackground(new java.awt.Color(255, 255, 255));
        txtBulanCad.setForeground(new java.awt.Color(0, 0, 0));
        pnlCadangan.add(txtBulanCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNmKplCad.setBackground(new java.awt.Color(255, 255, 255));
        txtNmKplCad.setForeground(new java.awt.Color(0, 0, 0));
        txtNmKplCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNmKplCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(txtNmKplCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtTahunCad.setBackground(new java.awt.Color(255, 255, 255));
        txtTahunCad.setForeground(new java.awt.Color(0, 0, 0));
        pnlCadangan.add(txtTahunCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsCad.setText("HAPUS");
        btnHpsCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(btnHpsCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 80, -1));

        btnSmpnCad.setText("SIMPAN");
        btnSmpnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(btnSmpnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        btnUbhCad.setText("UBAH");
        btnUbhCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(btnUbhCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 80, -1));

        txtCariCad.setBackground(new java.awt.Color(255, 255, 255));
        txtCariCad.setForeground(new java.awt.Color(0, 0, 0));
        txtCariCad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariCadKeyReleased(evt);
            }
        });
        pnlCadangan.add(txtCariCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, -1));

        tabelCadangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tabelCadangan);

        pnlCadangan.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 790, 155));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("ID Cadangan");
        pnlCadangan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtKdCad.setBackground(new java.awt.Color(255, 255, 255));
        txtKdCad.setForeground(new java.awt.Color(0, 0, 0));
        txtKdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(txtKdCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Luas");
        pnlCadangan.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Laut");
        pnlCadangan.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        txtLuasCad.setBackground(new java.awt.Color(255, 255, 255));
        txtLuasCad.setForeground(new java.awt.Color(0, 0, 0));
        pnlCadangan.add(txtLuasCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 220, -1));

        txtLautCad.setBackground(new java.awt.Color(255, 255, 255));
        txtLautCad.setForeground(new java.awt.Color(0, 0, 0));
        txtLautCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLautCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(txtLautCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("No IUP");
        pnlCadangan.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtNoIupCad.setBackground(new java.awt.Color(255, 255, 255));
        txtNoIupCad.setForeground(new java.awt.Color(0, 0, 0));
        txtNoIupCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoIupCadActionPerformed(evt);
            }
        });
        pnlCadangan.add(txtNoIupCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Target Hari Gali");
        pnlCadangan.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, -1));

        txtDdh.setBackground(new java.awt.Color(255, 255, 255));
        txtDdh.setForeground(new java.awt.Color(0, 0, 0));
        pnlCadangan.add(txtDdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 220, -1));

        jLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 0, 0));
        jLabel.setText("Produksi Harapan");
        pnlCadangan.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 150, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Target Kadar Timah");
        pnlCadangan.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        txtPdh.setBackground(new java.awt.Color(255, 255, 255));
        txtPdh.setForeground(new java.awt.Color(0, 0, 0));
        pnlCadangan.add(txtPdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 220, -1));

        txtTdh.setBackground(new java.awt.Color(255, 255, 255));
        txtTdh.setForeground(new java.awt.Color(0, 0, 0));
        txtTdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTdhActionPerformed(evt);
            }
        });
        pnlCadangan.add(txtTdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 220, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Target Isi/Volume");
        pnlCadangan.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        txtIdh.setBackground(new java.awt.Color(255, 255, 255));
        txtIdh.setForeground(new java.awt.Color(0, 0, 0));
        txtIdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdhActionPerformed(evt);
            }
        });
        pnlCadangan.add(txtIdh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 220, -1));

        Content.add(pnlCadangan, "card5");

        pnlRealisasi.setBackground(new java.awt.Color(204, 204, 204));
        pnlRealisasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Isi Sebenarnya");
        pnlRealisasi.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Dredging Sebenarnya");
        pnlRealisasi.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 180, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Kode Cadangan");
        pnlRealisasi.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtDsb.setBackground(new java.awt.Color(255, 255, 255));
        txtDsb.setForeground(new java.awt.Color(0, 0, 0));
        pnlRealisasi.add(txtDsb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 220, -1));

        txtKdCadReal.setBackground(new java.awt.Color(255, 255, 255));
        txtKdCadReal.setForeground(new java.awt.Color(0, 0, 0));
        txtKdCadReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdCadRealActionPerformed(evt);
            }
        });
        pnlRealisasi.add(txtKdCadReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 220, -1));

        txtIsb.setBackground(new java.awt.Color(255, 255, 255));
        txtIsb.setForeground(new java.awt.Color(0, 0, 0));
        pnlRealisasi.add(txtIsb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 220, -1));

        btnHpsReal.setText("HAPUS");
        btnHpsReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsRealActionPerformed(evt);
            }
        });
        pnlRealisasi.add(btnHpsReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 80, -1));

        btnSmpnReal.setText("SIMPAN");
        btnSmpnReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnRealActionPerformed(evt);
            }
        });
        pnlRealisasi.add(btnSmpnReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        btnUbhReal.setText("UBAH");
        btnUbhReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhRealActionPerformed(evt);
            }
        });
        pnlRealisasi.add(btnUbhReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 80, -1));

        txtCariReal.setBackground(new java.awt.Color(255, 255, 255));
        txtCariReal.setForeground(new java.awt.Color(0, 0, 0));
        txtCariReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariRealKeyReleased(evt);
            }
        });
        pnlRealisasi.add(txtCariReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 440, -1));

        tabelReal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelReal);

        pnlRealisasi.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 560, 155));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("ID Realisasi");
        pnlRealisasi.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtKdReal.setBackground(new java.awt.Color(255, 255, 255));
        txtKdReal.setForeground(new java.awt.Color(0, 0, 0));
        txtKdReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKdRealActionPerformed(evt);
            }
        });
        pnlRealisasi.add(txtKdReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 220, -1));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Produksi Sebenarnya");
        pnlRealisasi.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 180, -1));

        txtPsb.setBackground(new java.awt.Color(255, 255, 255));
        txtPsb.setForeground(new java.awt.Color(0, 0, 0));
        pnlRealisasi.add(txtPsb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, -1));

        txtTsb.setBackground(new java.awt.Color(255, 255, 255));
        txtTsb.setForeground(new java.awt.Color(0, 0, 0));
        txtTsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTsbActionPerformed(evt);
            }
        });
        pnlRealisasi.add(txtTsb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 220, -1));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Kadar Timah Sebenarnya");
        pnlRealisasi.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        Content.add(pnlRealisasi, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI MANAJEMEN TAMBANG");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnKapal.setBackground(new java.awt.Color(204, 204, 204));
        btnKapal.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKapal.setForeground(new java.awt.Color(0, 0, 0));
        btnKapal.setText("KAPAL");
        btnKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKapalActionPerformed(evt);
            }
        });

        btnIup.setBackground(new java.awt.Color(204, 204, 204));
        btnIup.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnIup.setForeground(new java.awt.Color(0, 0, 0));
        btnIup.setText("IUP");
        btnIup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIupActionPerformed(evt);
            }
        });

        btnCadangan.setBackground(new java.awt.Color(204, 204, 204));
        btnCadangan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCadangan.setForeground(new java.awt.Color(0, 0, 0));
        btnCadangan.setText("CADANGAN");
        btnCadangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadanganActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnRealisasi.setBackground(new java.awt.Color(204, 204, 204));
        btnRealisasi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnRealisasi.setForeground(new java.awt.Color(0, 0, 0));
        btnRealisasi.setText("REALISASI");
        btnRealisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealisasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIup)
                    .addComponent(btnKapal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadangan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRealisasi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadangan, btnIup, btnKapal, btnRealisasi});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKapal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIup)
                .addGap(18, 18, 18)
                .addComponent(btnCadangan)
                .addGap(18, 18, 18)
                .addComponent(btnRealisasi)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadangan, btnIup, btnKapal, btnRealisasi});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKapalActionPerformed
        Content.removeAll(); 
        Content.add(pnlKapal);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKapalActionPerformed

    private void btnIupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIupActionPerformed
        Content.removeAll(); 
        Content.add(pnlIup);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnIupActionPerformed

    private void btnCadanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadanganActionPerformed
        Content.removeAll(); 
        Content.add(pnlCadangan);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnCadanganActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRealisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealisasiActionPerformed
        Content.removeAll(); 
        Content.add(pnlRealisasi);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnRealisasiActionPerformed

    private void txtCariKplKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKplKeyReleased
        String c = txtCariKpl.getText();
        String cari = "SELECT*FROM Kapal WHERE nm_kpl LIKE '%"+c+"%'"+
                      "OR instansi LIKE '%"+c+"%' OR dlm_gali LIKE '%"+c+"%'";
        mycode.tampilDataKapal(tabelKapal, cari);
    }//GEN-LAST:event_txtCariKplKeyReleased

    private void btnUbhKplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKplActionPerformed
        try {
            mycode.ubahKapal(txtNmKpl.getText(), txtInstansi.getText(), 
                             txtDlmGali.getText());

            // Refresh tabel
            mycode.tampilDataKapal(tabelKapal, "SELECT*FROM Kapal");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKplActionPerformed

    private void btnSmpnKplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKplActionPerformed
        try {
            if(txtNmKpl.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Kapal Belum Diisi");
                txtNmKpl.requestFocus();
            } else if(txtInstansi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Instansi Belum Diisi");
                txtInstansi.requestFocus();
            } else if(txtDlmGali.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Dalam Gali Belum Diisi");
                txtDlmGali.requestFocus();
            } else {
                mycode.simpanKapal02(txtNmKpl.getText(), txtInstansi.getText(), 
                                    txtDlmGali.getText()); 

                // Refresh tabel
                mycode.tampilDataKapal(tabelKapal, "SELECT*FROM Kapal");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtInstansi.setText(mycode.CEK_INSTANSI_KPL);
                    txtDlmGali.setText(mycode.CEK_DLM_GALI_KPL);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKplActionPerformed

    private void btnHpsKplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKplActionPerformed
        try {
            mycode.hapusKapal(txtNmKpl.getText());
            mycode.tampilDataKapal(tabelKapal, "SELECT*FROM Kapal");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKplActionPerformed

    private void txtInstansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstansiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstansiActionPerformed

    private void txtNmKplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmKplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmKplActionPerformed

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void btnHpsIupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsIupActionPerformed
        try {
            mycode.hapusIUP(txtNoIup.getText());
            mycode.tampilDataIUP(tabelIUP, "SELECT*FROM IUP");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsIupActionPerformed

    private void btnSmpnIupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnIupActionPerformed
        try {
            if(txtNoIup.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No IUP Belum Diisi");
                txtNoIup.requestFocus();
            } else if(txtLokasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Lokasi Belum Diisi");
                txtLokasi.requestFocus();
            } else if(txtNoSk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No SK Belum Diisi");
                txtNoSk.requestFocus();
            } else if(txtTglBerlaku.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tgl Berlaku Belum Diisi");
                txtTglBerlaku.requestFocus();
            } else if(txtNoSert.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Sertifikat Belum Diisi");
                txtNoSert.requestFocus();
            } else if(txtKet.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Keterangan Belum Diisi");
                txtKet.requestFocus();
            } else {
                mycode.simpanIUP02(txtNoIup.getText(), txtLokasi.getText(),
                                   txtNoSk.getText(), txtTglBerlaku.getText(),
                                   txtNoSert.getText(), txtKet.getText());

                // Refresh tabel
                mycode.tampilDataIUP(tabelIUP, "SELECT*FROM IUP");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtLokasi.setText(mycode.CEK_LOKASI_IUP);
                    txtNoSk.setText(mycode.CEK_NO_SK_IUP);
                    txtTglBerlaku.setText(mycode.CEK_TGL_BERLAKU_IUP);
                    txtNoSert.setText(mycode.CEK_NO_SERT_IUP);
                    txtKet.setText(mycode.CEK_KET_IUP);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnIupActionPerformed

    private void btnUbhIupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhIupActionPerformed
        try {
            mycode.ubahIUP(txtNoIup.getText(), txtLokasi.getText(),
                           txtNoSk.getText(), txtTglBerlaku.getText(),
                           txtNoSert.getText(), txtKet.getText());

            // Refresh tabel
            mycode.tampilDataIUP(tabelIUP, "SELECT*FROM IUP");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhIupActionPerformed

    private void txtCariIupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariIupKeyReleased
        String c = txtCariIup.getText();
        String cari = "SELECT*FROM IUP WHERE no_iup LIKE '%"+c+"%'"+
                      "OR lokasi LIKE '%"+c+"%' OR no_sk LIKE '%"+c+"%'"+
                      "OR tgl_berlaku LIKE '%"+c+"%' OR no_sert LIKE '%"+c+"%'"+
                      "OR ket LIKE '%"+c+"%'";
        mycode.tampilDataIUP(tabelIUP, cari);
    }//GEN-LAST:event_txtCariIupKeyReleased

    private void txtNoIupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoIupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoIupActionPerformed

    private void txtNmKplCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNmKplCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNmKplCadActionPerformed

    private void btnHpsCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsCadActionPerformed
        try {
            mycode.hapusCadangan(txtKdCad.getText());
            mycode.tampilDataCadangan(tabelCadangan, "SELECT*FROM Cadangan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsCadActionPerformed

    private void btnSmpnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnCadActionPerformed
        try {
            if(txtKdCad.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kode Cadangan Belum Diisi");
                txtKdCad.requestFocus();
            } else if(txtNmKplCad.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Nama Kapal Belum Diisi");
                txtNmKplCad.requestFocus();
            } else if(txtBulanCad.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Bulan Belum Diisi");
                txtBulanCad.requestFocus();
            } else if(txtTahunCad.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tahun Belum Diisi");
                txtTahunCad.requestFocus();
            } else if(txtNoIupCad.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "No IUP Belum Diisi");
                txtNoIupCad.requestFocus();
            } else if(txtLautCad.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Laut Belum Diisi");
                txtLautCad.requestFocus();
            } else if(txtLuasCad.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Luas Belum Diisi");
                txtLuasCad.requestFocus();
            } else if(txtDdh.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "DDH Belum Diisi");
                txtDdh.requestFocus();
            } else if(txtIdh.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "IDH Belum Diisi");
                txtIdh.requestFocus();
            } else if(txtTdh.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "TDH Belum Diisi");
                txtTdh.requestFocus();
            } else if(txtPdh.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "PDH Belum Diisi");
                txtPdh.requestFocus();
            } else {
                mycode.simpanCadangan02(txtKdCad.getText(), txtNmKplCad.getText(),
                                      txtBulanCad.getText(), txtTahunCad.getText(),
                                      txtNoIupCad.getText(), txtLautCad.getText(),
                                      txtLuasCad.getText(), txtDdh.getText(),
                                      txtIdh.getText(), txtTdh.getText(), txtPdh.getText());

                // Refresh tabel
                mycode.tampilDataCadangan(tabelCadangan, "SELECT*FROM Cadangan");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtNmKplCad.setText(mycode.CEK_NM_KPL_CAD);
                    txtBulanCad.setText(mycode.CEK_BULAN_CAD);
                    txtTahunCad.setText(mycode.CEK_TAHUN_CAD);
                    txtNoIupCad.setText(mycode.CEK_NO_IUP_CAD);
                    txtLautCad.setText(mycode.CEK_LAUT_CAD);
                    txtLuasCad.setText(mycode.CEK_LUAS_CAD);
                    txtDdh.setText(mycode.CEK_DDH_CAD);
                    txtIdh.setText(mycode.CEK_IDH_CAD);
                    txtTdh.setText(mycode.CEK_TDH_CAD);
                    txtPdh.setText(mycode.CEK_PDH_CAD);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnCadActionPerformed

    private void btnUbhCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhCadActionPerformed
        try {
            mycode.ubahCadangan(txtKdCad.getText(), txtNmKplCad.getText(),
                                  txtBulanCad.getText(), txtTahunCad.getText(),
                                  txtNoIupCad.getText(), txtLautCad.getText(),
                                  txtLuasCad.getText(), txtDdh.getText(),
                                  txtIdh.getText(), txtTdh.getText(), txtPdh.getText());

            // Refresh tabel
            mycode.tampilDataCadangan(tabelCadangan, "SELECT*FROM Cadangan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhCadActionPerformed

    private void txtCariCadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariCadKeyReleased
        String c = txtCariCad.getText();
        String cari = "SELECT*FROM Cadangan WHERE kd_cad LIKE '%"+c+"%'"+
                      "OR nm_kpl LIKE '%"+c+"%' OR bulan LIKE '%"+c+"%'"+
                      "OR tahun LIKE '%"+c+"%' OR no_iup LIKE '%"+c+"%'"+
                      "OR laut LIKE '%"+c+"%' OR luas LIKE '%"+c+"%'"; // Dibatasi agar tidak terlalu panjang
        mycode.tampilDataCadangan(tabelCadangan, cari);
    }//GEN-LAST:event_txtCariCadKeyReleased

    private void txtKdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdCadActionPerformed

    private void txtKdCadRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdCadRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdCadRealActionPerformed

    private void btnHpsRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsRealActionPerformed
        try {
            mycode.hapusRealisasi(txtKdReal.getText());
            mycode.tampilDataRealisasi(tabelReal, "SELECT*FROM Realisasi");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsRealActionPerformed

    private void btnSmpnRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnRealActionPerformed
        try {
            if(txtKdReal.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kode Realisasi Belum Diisi");
                txtKdReal.requestFocus();
            } else if(txtKdCadReal.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Kode Cadangan Belum Diisi");
                txtKdCadReal.requestFocus();
            } else if(txtDsb.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "DSB Belum Diisi");
                txtDsb.requestFocus();
            } else if(txtIsb.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ISB Belum Diisi");
                txtIsb.requestFocus();
            } else if(txtTsb.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "TSB Belum Diisi");
                txtTsb.requestFocus();
            } else if(txtPsb.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "PSB Belum Diisi");
                txtPsb.requestFocus();
            } else {
                mycode.simpanRealisasi02(txtKdReal.getText(), txtKdCadReal.getText(),
                                         txtDsb.getText(), txtIsb.getText(),
                                         txtTsb.getText(), txtPsb.getText());

                // Refresh tabel
                mycode.tampilDataRealisasi(tabelReal, "SELECT*FROM Realisasi");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtKdCadReal.setText(mycode.CEK_KD_CAD_REAL);
                    txtDsb.setText(mycode.CEK_DSB_REAL);
                    txtIsb.setText(mycode.CEK_ISB_REAL);
                    txtTsb.setText(mycode.CEK_TSB_REAL);
                    txtPsb.setText(mycode.CEK_PSB_REAL);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnRealActionPerformed

    private void btnUbhRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhRealActionPerformed
        try {
            mycode.ubahRealisasi(txtKdReal.getText(), txtKdCadReal.getText(),
                                 txtDsb.getText(), txtIsb.getText(),
                                 txtTsb.getText(), txtPsb.getText());

            // Refresh tabel
            mycode.tampilDataRealisasi(tabelReal, "SELECT*FROM Realisasi");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhRealActionPerformed

    private void txtCariRealKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariRealKeyReleased
        String c = txtCariReal.getText();
        String cari = "SELECT*FROM Realisasi WHERE kd_real LIKE '%"+c+"%'"+
                      "OR kd_cad LIKE '%"+c+"%' OR dsb LIKE '%"+c+"%'"+
                      "OR tsb LIKE '%"+c+"%'";
        mycode.tampilDataRealisasi(tabelReal, cari);
    }//GEN-LAST:event_txtCariRealKeyReleased

    private void txtKdRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKdRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKdRealActionPerformed

    private void txtTsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTsbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTsbActionPerformed

    private void txtLautCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLautCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLautCadActionPerformed

    private void txtNoIupCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoIupCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoIupCadActionPerformed

    private void txtTdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTdhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTdhActionPerformed

    private void txtIdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnCadangan;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsCad;
    private javax.swing.JButton btnHpsIup;
    private javax.swing.JButton btnHpsKpl;
    private javax.swing.JButton btnHpsReal;
    private javax.swing.JButton btnIup;
    private javax.swing.JButton btnKapal;
    private javax.swing.JButton btnRealisasi;
    private javax.swing.JButton btnSmpnCad;
    private javax.swing.JButton btnSmpnIup;
    private javax.swing.JButton btnSmpnKpl;
    private javax.swing.JButton btnSmpnReal;
    private javax.swing.JButton btnUbhCad;
    private javax.swing.JButton btnUbhIup;
    private javax.swing.JButton btnUbhKpl;
    private javax.swing.JButton btnUbhReal;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pnlCadangan;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlIup;
    private javax.swing.JPanel pnlKapal;
    private javax.swing.JPanel pnlRealisasi;
    private javax.swing.JTable tabelCadangan;
    private javax.swing.JTable tabelIUP;
    private javax.swing.JTable tabelKapal;
    private javax.swing.JTable tabelReal;
    private javax.swing.JTextField txtBulanCad;
    private javax.swing.JTextField txtCariCad;
    private javax.swing.JTextField txtCariIup;
    private javax.swing.JTextField txtCariKpl;
    private javax.swing.JTextField txtCariReal;
    private javax.swing.JTextField txtDdh;
    private javax.swing.JTextField txtDlmGali;
    private javax.swing.JTextField txtDsb;
    private javax.swing.JTextField txtIdh;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtIsb;
    private javax.swing.JTextField txtKdCad;
    private javax.swing.JTextField txtKdCadReal;
    private javax.swing.JTextField txtKdReal;
    private javax.swing.JTextField txtKet;
    private javax.swing.JTextField txtLautCad;
    private javax.swing.JTextField txtLokasi;
    private javax.swing.JTextField txtLuasCad;
    private javax.swing.JTextField txtNmKpl;
    private javax.swing.JTextField txtNmKplCad;
    private javax.swing.JTextField txtNoIup;
    private javax.swing.JTextField txtNoIupCad;
    private javax.swing.JTextField txtNoSert;
    private javax.swing.JTextField txtNoSk;
    private javax.swing.JTextField txtPdh;
    private javax.swing.JTextField txtPsb;
    private javax.swing.JTextField txtTahunCad;
    private javax.swing.JTextField txtTdh;
    private javax.swing.JTextField txtTglBerlaku;
    private javax.swing.JTextField txtTsb;
    // End of variables declaration//GEN-END:variables
}
